name: 'minikube-wait-action'
description: 'Waits for Github Actions started Kubernetes pods to be in a healthy state.'
branding:
  icon: 'watch'
  color: 'blue'
inputs:
  max-retry-attempts:
    description: 'Maximum of times the check can be carried on.'
    required: false
    default: 10
  retry-delay:
    description: 'Time to wait (in seconds) before attempting the check after a failure.'
    required: false
    default: 30
runs:
  using: 'node12'
  main: 'src/index.js'